### ISSUE TITLE
댓글 작성자가 본인인지 판별하기 어렵습니다.

### ISSUE THREAD

**Issue by Mindohyeon** [SLTDV/Choice-BackEnd#122]
## :bug: BUG
댓글 작성자가 본인인지 확인하려면 게시물 삭제 요청을 해야합니다. 이로인해 불필요한 리소스가 발생합니다.

## Description
기획된 내용은 내 댓글이 아니면 swipe action 자체가 불가능해야하는데,
현재 API 상으로는 댓글 삭제를 요청해야 그 댓글이 본인 것인지 판별할 수 있습니다.

<img width="415" alt="스크린샷 2023-04-05 오후 12 21 13" src="https://user-images.githubusercontent.com/81687906/229973162-1f68fb36-f58e-4527-89de-a713b0109c7d.png">

### 요청
때문에 댓글 API에 작성자가 본인인지 확인할 수 있는 ```isMine``` 을 추가하면 어떨까요?

**Comment by shgur7236** [comment]
<img width="334" alt="스크린샷 2023-04-05 오후 12 24 16" src="https://user-images.githubusercontent.com/81364498/229973493-42f4d9ab-33b4-4ddd-ae87-7a5d1ef78aae.png">
이렇게 수정할게요!
